# Generated by Django 2.1.7 on 2020-03-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture_orm_extended', '0002_auto_20200309_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperDummy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='number_of_articles',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='number_of_classes',
            field=models.IntegerField(default=0),
        ),
    ]
