# Generated by Django 2.1.7 on 2020-03-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture_orm_extended', '0003_auto_20200309_0234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuperDummy',
        ),
        migrations.AlterField(
            model_name='student',
            name='number_of_articles',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='student',
            name='number_of_classes',
            field=models.IntegerField(default=4),
        ),
    ]
